metrics:

  roe:
    column: roe
    operator: min

  debt_equity:
    column: debt_equity
    operator: max

  free_cash_flow:
    column: free_cash_flow
    operator: min

  revenue_cagr_5y:
    column: revenue_cagr_5y
    operator: min

  pat_cagr_5y:
    column: pat_cagr_5y
    operator: min

  opm:
    column: opm
    operator: min

  pe:
    column: pe_ratio
    operator: max

  pb:
    column: pb_ratio
    operator: max

  dividend_yield:
    column: dividend_yield
    operator: min

  interest_coverage:
    column: interest_coverage
    operator: min

  market_cap:
    column: market_cap
    operator: min

  net_profit:
    column: net_profit
    operator: min

  eps_cagr:
    column: eps_cagr_5y
    operator: min

  asset_turnover:
    column: asset_turnover
    operator: min

  sales:
    column: sales
    operator: min